# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '7.x'
  displayName: 'Deploy my app'

- script: |
    npm install
    npm run build
    npm run test
    echo here at the end of the script
  displayName: 'npm test and build'
